name: 'Datadog CI'
description: 'Execute commands from your Continuous Integration (CI) and Continuous Delivery (CD) pipelines to integrate with existing Datadog products.'
inputs:
  DD_SITE:
    required: false
    default: 'us3.datadoghq.com'
  COMMAND:
    required: true

permissions:
  contents: read
  id-token: write

runs:
  using: "composite"
  steps:
    - name: Assume AWS management account role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::865076270365:role/github-ci-datadog-api-key-read-role
        aws-region: eu-west-1
        role-session-name: "GitHubActions-DeployLayerStack"
        unset-current-credentials: true
    
    - name: Read Datadog AWS Secret value
      id: dd_api_key
      run: |
        DD_API_KEY=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:eu-west-1:865076270365:secret:DatadogGithubActionsApiKey-prGZpR --query SecretString --output text)
        echo "::add-mask::$DD_API_KEY"
        echo "DD_API_KEY=$DD_API_KEY" >> $GITHUB_OUTPUT
      shell: bash

    - name: Executing Datadog CI
      run: |
        if ! which datadog-ci > /dev/null 2>&1; then
          echo "Datadog CI is not installed. Proceeding with installation..."
          if curl -L --fail "https://github.com/DataDog/datadog-ci/releases/latest/download/datadog-ci_linux-x64" --output "/usr/local/bin/datadog-ci" && chmod +x /usr/local/bin/datadog-ci; then
            echo "Datadog CI has been successfully installed."
          else
            echo "Failed to install Datadog CI. Please check your installation process."
            exit 0
          fi
        else
          echo "Datadog CI is already installed."
        fi

        if which datadog-ci > /dev/null 2>&1; then
          datadog-ci ${{ inputs.COMMAND }} || echo "Failed to execute Datadog CI command."
        else
          echo "Datadog CI is not installed. Skipping execution of command."
          exit 0
        fi
      shell: bash
      env:
          DD_SITE: ${{ inputs.DD_SITE }}
          DD_API_KEY: ${{ steps.dd_api_key.outputs.DD_API_KEY }}
