parameters:
  - name: jobName
    type: string
    default: "datadog_ci"

  - name: displayName
    type: string
    default: "Datadog CI execution"
  
  - name: pool
    type: string
    default: "Development Pipeline"
  
  - name: DD_API_KEY
    type: string
  
  - name: DD_SITE
    type: string
    default: "us3.datadoghq.com"

  - name: COMMAND
    type: string

jobs:
  - job: '${{ parameters.jobName }}'
    displayName: '${{ parameters.displayName }}'
    pool: '${{ parameters.pool }}'
    timeoutInMinutes: 2

    steps:
      - checkout: none

      - task: Bash@3
        inputs:
          targetType: 'inline'
          failOnStderr: false
          script: |
            if ! which datadog-ci > /dev/null 2>&1; then
              echo "Datadog CI is not installed. Proceeding with installation..."
              if curl -L --fail "https://github.com/DataDog/datadog-ci/releases/latest/download/datadog-ci_linux-x64" --output "/usr/local/bin/datadog-ci" && chmod +x /usr/local/bin/datadog-ci; then
                echo "Datadog CI has been successfully installed."
              else
                echo "Failed to install Datadog CI. Please check your installation process."
                exit 0
              fi
            else
              echo "Datadog CI is already installed."
            fi

            if which datadog-ci > /dev/null 2>&1; then
              datadog-ci $COMMAND || echo "Failed to execute Datadog CI command."
            else
              echo "Datadog CI is not installed. Skipping execution of command."
              exit 0
            fi
        displayName: 'Add tags to job traces'
        env:
          DD_API_KEY: "${{ parameters.DD_API_KEY }}"
          DD_SITE: "${{ parameters.DD_SITE }}"
          COMMAND: "${{ parameters.COMMAND }}"
