parameters:
  - name: jobName
    type: string
    default: "datadog_ci"

  - name: displayName
    type: string
    default: "Datadog CI execution"
  
  - name: DD_API_KEY
    type: string
  
  - name: DD_SITE
    type: string
    default: "us3.datadoghq.com"

  - name: COMMAND
    type: string

jobs:
  - job: '${{ parameters.jobName }}'
    displayName: '${{ parameters.displayName }}'
    pool: Development Pipeline
    timeoutInMinutes: 1

    steps:
      - checkout: none

      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            if ! which datadog-ci > /dev/null 2>&1; then
              echo "Datadog CI is not installed. Proceeding with installation..."
              curl -L --fail "https://github.com/DataDog/datadog-ci/releases/latest/download/datadog-ci_linux-x64" --output "/usr/local/bin/datadog-ci" && chmod +x /usr/local/bin/datadog-ci
    
              if [ $? -eq 0 ]; then
                echo "Datadog CI has been successfully installed."
              else
                echo "Failed to install Datadog CI. Please check your installation process."
                exit 1
              fi
            else
              echo "Datadog CI is already installed."
            fi
        displayName: 'Install datadog-ci'

      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'datadog-ci $COMMAND'
        displayName: 'Add tags to job traces'
        env:
          DD_API_KEY: "${{ parameters.DD_API_KEY }}"
          DD_SITE: "${{ parameters.DD_SITE }}"
          COMMAND: "${{ parameters.COMMAND }}"
